---
# Copyright (C) 2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- name: Create configuration directories (Arch Linux / FreeBSD)
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: "{{ dovecot_root_group }}"
    mode: '0755'
  loop:
    - "{{ dovecot_configuration_directory }}"
    - "{{ dovecot_configuration_directory }}/conf.d"
  when: ansible_os_family in ['Archlinux', 'FreeBSD']

- name: Setup main configuration file
  template:
    src: dovecot.conf.j2
    dest: "{{ dovecot_configuration_directory }}/dovecot.conf"
    owner: root
    group: "{{ dovecot_root_group }}"
    mode: '0664'
  notify: restart dovecot
  when: ansible_os_family == 'Archlinux'

- name: Setup master configuration
  template:
    src: master.conf.j2
    dest: "{{ dovecot_configuration_directory }}/conf.d/10-master.conf"
    owner: root
    group: "{{ dovecot_root_group }}"
    mode: '0664'
  notify: restart dovecot

- name: Setup authentication configuration
  template:
    src: auth.conf.j2
    dest: "{{ dovecot_configuration_directory }}/conf.d/10-auth.conf"
    group: "{{ dovecot_root_group }}"
    mode: '0664'
  notify: restart dovecot

- name: Setup various authentication methods
  template:
    src: "auth-{{ item }}.conf.ext.j2"
    dest: "{{ dovecot_configuration_directory }}/conf.d/auth-{{ item }}.conf.ext"
    group: "{{ dovecot_root_group }}"
    mode: '0664'
  loop: "{{ dovecot_available_databases }}"

- name: Configure stats
  template:
    src: local.conf.j2
    dest: "{{ dovecot_configuration_directory }}/local.conf"
    owner: root
    group: "{{ dovecot_root_group }}"
    mode: '0664'
  notify: restart dovecot
