---
# Copyright (C) 2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- import_tasks: vmail-user.yml

- name: Ensure that dovecot is installed
  package:
    name: "{{ dovecot_packages }}"
    state: present

