---
# Copyright (C) 2021-2025 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- import_tasks: vmail-user.yml

- name: Ensure that dovecot is installed
  package:
    name: "{{ dovecot_packages }}"
    state: present

- name: Configure Dovecot
  import_tasks: conf.yml

- name: Exim śupport
  import_tasks: exim.yml
  when: dovecot_exim_support is sameas true

- name: Ensure that Dovecot is enabled and started
  service:
    name: dovecot
    state: started
    enabled: true
